### ISSUE TITLE
Erro quando se instala o WooCommerce Boleto também

### ISSUE THREAD

**Issue by raptavares** [matheusgimenez/woocommerce-boleto-parcelado#1]
Não é possível ativar o plugin

Fatal error: Cannot redeclare wcboleto_assets_url() (previously declared in /home/raptavares/webapps/boletoparcelado/wp-content/plugins/woocommerce-boleto-parcelado-master/woocommerce-boleto-parcelado.php:242) in /home/raptavares/webapps/boletoparcelado/wp-content/plugins/woocommerce-boleto/woocommerce-boleto.php on line 243

**Comment by matheusgimenez** [comment]
Resolvido

**Comment by raptavares** [comment]
é possível ativar o plugin original (Boleto) simultaneamente com o plugin novo (Boleto Parcelado), mas não é possível usar o primeiro como uma forma de pagamento nas opções de Finalização de Compra. Mesmo estando ambos ativos, somente o Boleto Parcelado consta como opção.

Aí abrindo para configurar o Boleto Parcelado, na verdade, as configurações são do plugin original (Boleto).

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by raptavares** [comment]
Com os dois plugins ativos, acontece um erro no checkout, pois selecionando o "Boleto Bancário" surgem dois botões "Pagar Boleto", um é referente ao plugin "Boleto Bancário" e o outro é referente ao plugin "Boleto Bancário Parcelado".

Veja:

![captura de tela 2015-05-05 as 18 34 21](https://cloud.githubusercontent.com/assets/8008944/7483477/a5df65e0-f355-11e4-8bfc-5ee86de26f6b.png)
