### ISSUE TITLE
Código de barras do boleto não está gerado

### ISSUE THREAD

**Issue by raptavares** [matheusgimenez/woocommerce-boleto-parcelado#2]
O plugin gera todos os boletos, mas todos eles:
- sem códigos de barras
- sem linhas digitáveis. 
- sem número da agência e conta

Veja anexo:

![boleto parcelado](https://cloud.githubusercontent.com/assets/8008944/6925337/269c2b26-d7b5-11e4-8bef-6435193feae4.png)

**Comment by matheusgimenez** [comment]
Como disse no telegram, o problema é com o arquivo functions dentro da pasta do banco selecionado, to com umas ideias em mente pra ajustar ele, a noite devo corrigir isso sem problemas

**Comment by matheusgimenez** [comment]
feito no ultimo commit.. agora falta testar mt hehe
