### ISSUE TITLE
Tradução pt_br do plugin não disponível

### ISSUE THREAD

**Issue by raptavares** [matheusgimenez/woocommerce-boleto-parcelado#3]
Precisamos traduzir, né? No ambiente de testes, ele está em inglês.

**Comment by matheusgimenez** [comment]
Preciso declarar o texto domain

**Comment by matheusgimenez** [comment]
Estou fazendo essa nesse momento.. preciso traduzir as strings novas que adicionei

**Comment by matheusgimenez** [comment]
Fiz no ultimo commit.. agora creio que todos issues foram resolvidos
