### ISSUE TITLE
Inserção de juros opcionais não disponível

### ISSUE THREAD

**Issue by raptavares** [matheusgimenez/woocommerce-boleto-parcelado#4]
Precisamos implementar

**Comment by matheusgimenez** [comment]
Me explica melhor isso.. o plugin original tem essa função?

**Comment by raptavares** [comment]
Não não... isso estava no PDF que te mandei.

É necessário uma opção para a pessoa inserir um valor numérico que adiciona um juros na parcela. Por exemplo: a pessoa insere 3% de juros e cada parcela terá um acréscimo de 3%.

**Comment by matheusgimenez** [comment]
Eu vi no PDF, eu queria saber exatamente o que falou, se o plugin já tinha ou não. Mas eu crio sem problemas, é coisa simples. :)

**Comment by raptavares** [comment]
Testei essa funcionalidade e precisamos de 2 coisas:
1. Na seleção do parcelamento, exibir 1x de R$ XX,XX (sem juros); 2x de R$ XX,XX (10% de juros). Em 10% de juros, exibir a taxa inserida pelo administrador.
2. Juros só está sendo adicionado na segunda parcela em diante. Quando se seleciona 1x, está ok. Porém, em mais de uma parcela, o juros só está incluso na segunda parcela em diante.

**Comment by matheusgimenez** [comment]
Beleza.. a noite removo esses bugs :)

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by raptavares** [comment]
@matheusgimenez, perfeito! Testei e está funcional... vou encaminhar a nova versão para o cliente!

**Comment by raptavares** [comment]
Quando a taxa de juros é zero (Backend), no frontend o valor de cada parcela mostra um abre e fecha parenteses vazio. 

Entendo que entre parênteses, deveria aparecer a taxa de juros. No caso do 0, não há, deveria aparecer “sem juros”.

**Comment by matheusgimenez** [comment]
feito no ultimo commit

**Comment by raptavares** [comment]
Texto entre parênteses está ok.

Porém, o juros não está sendo aplicado na opção de uma parcela.

Veja:

![captura de tela 2015-05-05 as 18 44 08](https://cloud.githubusercontent.com/assets/8008944/7483623/bd95b3b4-f356-11e4-94e6-a299d7d2a89f.png)
