### ISSUE TITLE
Correção da data de vencimento do boleto

### ISSUE THREAD

**Issue by raptavares** [matheusgimenez/woocommerce-boleto-parcelado#5]
A data do vencimento dos boletos deve ser da seguinte forma:
- Vencimento do primeiro boleto: 5 dias da compra
- Vencimento dos demais boletos: 30 em 30 dias

Então, se a compra é hoje, dia 31/03:

Boleto 1: 05/04
Boleto 2: 05/05
Boleto 3: 05/06 ....

O vencimento do boleto 2 tem que ser data da compra + 5 dias + 30 dias...

**Comment by matheusgimenez** [comment]
Eu ajustei isso do segundo boleto colocando um option também e esse option está ajustado por default em 35 dias

**Comment by raptavares** [comment]
Joia!
