### ISSUE TITLE
Transformar a opção valor mínimo em valor mínimo por parcela

### ISSUE THREAD

**Issue by raptavares** [matheusgimenez/woocommerce-boleto-parcelado#8]
Ao invés do campo valor mínimo para a opção aparecer, o que precisamos é a opção valor mínimo da parcela. Ele atuaria junto com a limitação de máximo de parcelas.

Exemplo:

(a) O parcelamento máximo é em 10x. (b) A parcela mínima é R$ 200,00.

A compra deu R$ 1700,00. Nesse caso usando os limites (a) e (b), oferecemos um parcelamento de até 8 vezes.

**Comment by matheusgimenez** [comment]
Pensei na seguinte lógica: diferente de hoje, o boleto vai aparecer em todos valores, ai faço um for pra pegar o numero maximo de parcelas.

Pode ser assim?

To no aguardo

**Comment by raptavares** [comment]
Perfeito!
Em 25/04/2015 14:27, "Matheus Gimenez Petroni" notifications@github.com
escreveu:
